
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Button unpack_button;
	
	private global::Gtk.Button import_button;
	
	private global::Gtk.Button save_button;
	
	private global::Gtk.Button refresh_button;
	
	private global::Gtk.ProgressBar progressbar;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView textview;
	
	private global::Gtk.Label label1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = "リース、ウォードの死亡";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.unpack_button = new global::Gtk.Button ();
		this.unpack_button.CanFocus = true;
		this.unpack_button.Name = "unpack_button";
		this.unpack_button.UseUnderline = true;
		this.unpack_button.Label = global::Mono.Unix.Catalog.GetString ("Unpack");
		this.hbox3.Add (this.unpack_button);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.unpack_button]));
		w1.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.import_button = new global::Gtk.Button ();
		this.import_button.CanFocus = true;
		this.import_button.Name = "import_button";
		this.import_button.UseUnderline = true;
		this.import_button.Label = global::Mono.Unix.Catalog.GetString ("Import");
		this.hbox3.Add (this.import_button);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.import_button]));
		w2.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.save_button = new global::Gtk.Button ();
		this.save_button.CanFocus = true;
		this.save_button.Name = "save_button";
		this.save_button.UseUnderline = true;
		this.save_button.Label = global::Mono.Unix.Catalog.GetString ("Make");
		this.hbox3.Add (this.save_button);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.save_button]));
		w3.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.refresh_button = new global::Gtk.Button ();
		this.refresh_button.CanFocus = true;
		this.refresh_button.Name = "refresh_button";
		this.refresh_button.UseUnderline = true;
		this.refresh_button.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		this.hbox3.Add (this.refresh_button);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.refresh_button]));
		w4.Position = 3;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.progressbar = new global::Gtk.ProgressBar ();
		this.progressbar.Name = "progressbar";
		this.progressbar.Text = global::Mono.Unix.Catalog.GetString ("Status: Ready");
		this.vbox1.Add (this.progressbar);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.progressbar]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview = new global::Gtk.TextView ();
		this.textview.CanFocus = true;
		this.textview.Name = "textview";
		this.textview.Editable = false;
		this.textview.CursorVisible = false;
		this.GtkScrolledWindow.Add (this.textview);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w8.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 547;
		this.DefaultHeight = 282;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.unpack_button.Clicked += new global::System.EventHandler (this.OnUnpackButtonClicked);
		this.import_button.Clicked += new global::System.EventHandler (this.OnImportButtonClicked);
		this.save_button.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
		this.refresh_button.Clicked += new global::System.EventHandler (this.OnRefreshButtonClicked);
	}
}
