
// This file has been generated by the GUI designer. Do not modify.
namespace TuBS
{
	public partial class ActionGroup
	{
		public virtual void Build ()
		{
			// Action group TuBS.ActionGroup
		}
	}
}
